[package]
name = "test_modules"
version = "0.1.0"
authors = ["vkhristenko <vdkhristenko1991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
function_name = "0.2.0"
